Description:  This template deploys a S3 bucket and creates a Glue IAM service role of the AWS Glue Project
Parameters:
  s3bucketforproject: 
    Description: Please enter the name for your S3 bucket. This will used throughout the "project" and must be unique globablly within AWS. 
    Type: String 

Resources:
  s3bucketforawsglueprojectrutika:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref s3bucketforproject
      Tags:
        - Key: "Project"
          Value: "AWSGlueRutikaRana"

  GlueIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSGlue
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AWSGlueProjectServicePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                  - lakeformation:*
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                  - s3:GetBucketAcl
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeRouteTables
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcAttribute
                  - iam:ListRolePolicies
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: 
                  - arn:aws:s3:::aws-glue-*/*
                  - arn:aws:s3:::*/*aws-glue-*/*
                  - !GetAtt s3bucketforawsglueprojectrutika.Arn
                  - !Join 
                    - ''
                    - - !GetAtt s3bucketforawsglueprojectrutika.Arn
                      - /*
              - Effect: Allow
                Action: 
                  - s3:GetObject
                Resource: 
                  - arn:aws:s3:::crawler-public*
                  - arn:aws:s3:::aws-glue-*
              - Effect: Allow 
                Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*:/aws-glue/*
              - Effect: Allow
                Action: 
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: 
                  - arn:aws:ec2:*:*:network-interface/*
                  - arn:aws:ec2:*:*:security-group/*
                  - arn:aws:ec2:*:*:instance/*
                Condition: 
                  ForAllValues:StringEquals:
                    aws:TagKeys:
                    - aws-glue-service-resource
                    
  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: AWSGlueProjectAthenaWorkgroup
      Description: The workgroup for the Rutika Rana aws glue project. 
      State: ENABLED
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: true
        ResultConfiguration:
          OutputLocation: !Sub s3://${s3bucketforawsglueprojectrutika}/athena
Outputs:
  S3Bucket:
    Description: A reference to the created S3 bucket
    Value: !Ref s3bucketforawsglueprojectrutika